name: CI

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    publish-marketplace:
        name: Release to marketplace
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://registry.npmjs.org/
            - name: Read package.json
              id: package
              uses: jaywcjlove/github-action-package@main
            - name: Configure PAT credentials
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: echo "@nguyenngoclongdev:registry=https://npm.pkg.github.com/" > .npmrc && echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
            - run: yarn install
            - name: Publish to Visual Studio Marketplace
              uses: HaaLeo/publish-vscode-extension@v1
              with:
                  pat: ${{ secrets.VSCE_PAT }}
                  registryUrl: https://marketplace.visualstudio.com
            - name: Publish to Open VSX Registry
              uses: HaaLeo/publish-vscode-extension@v1
              with:
                  pat: ${{ secrets.OPEN_VSX_TOKEN }}
            - name: Generate Changelog
              id: build_changelog
              uses: mikepenz/release-changelog-builder-action@v3
            - name: Create release note
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  name: v${{ steps.package.outputs.version }}
                  body: ${{ steps.build_changelog.outputs.changelog }}
                  draft: false
                  prerelease: false
                  files: ./${{ steps.package.outputs.name }}.vsix
