name: CI

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    publish-marketplace:
        name: Release to marketplace
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://registry.npmjs.org/
            - name: Setup Environment
              run: node -e "console.log('PACKAGE_VERSION=' + require('./package.json').version + '\nPACKAGE_NAME=' + require('./package.json').name + '-' + require('./package.json').version)" >> $GITHUB_ENV
            - name: Verify versions
              run: node -e "if ('refs/tags/v' + '${{ env.PACKAGE_VERSION }}' !== '${{ github.ref }}') { console.log('::error' + 'Version Mismatch. refs/tags/v' + '${{ env.PACKAGE_VERSION }}', '${{ github.ref }}'); throw Error('Version Mismatch')} "
            - name: Configure PAT credentials
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: echo "@nguyenngoclongdev:registry=https://npm.pkg.github.com/" > .npmrc && echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
            - run: yarn install
            - name: Publish to Visual Studio Marketplace
              uses: HaaLeo/publish-vscode-extension@v1
              with:
                  pat: ${{ secrets.VSCE_PAT }}
                  registryUrl: https://marketplace.visualstudio.com
            - name: Publish to Open VSX Registry
              uses: HaaLeo/publish-vscode-extension@v1
              with:
                  pat: ${{ secrets.OPEN_VSX_TOKEN }}
            - name: Generate Changelog
              id: changelog
              uses: mindsers/changelog-reader-action@v2
              with:
                  version: ${{ env.PACKAGE_VERSION }}
                  path: ./CHANGELOG.md
            - name: Create GitHub release
              id: create_release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  name: v${{ env.PACKAGE_VERSION }}
                  body: ${{ steps.changelog.outputs.changes }}
                  draft: false
                  prerelease: false
                  files: ./${{ env.PACKAGE_NAME }}.vsix
