name: CI

on:
    push:
        branches:
            - main

permissions:
    packages: write # publish package
    contents: write # to create release (changesets/action)
    pull-requests: write # to create pull request (changesets/action)

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://registry.npmjs.org/
            - name: Configure PAT credentials
              run: |
                  cat << EOF > "$HOME/.npmrc"
                    always-auth=true
                    @nguyenngoclongdev:registry=https://npm.pkg.github.com/
                    //npm.pkg.github.com/:_authToken=$NPM_TOKEN
                  EOF
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Install dependency
              run: yarn install --frozen-lockfile
            - name: Check style and format
              run: yarn lint
            - name: Test package before publish
              run: yarn test
            - name: Create Release Pull Request or publish package
              id: changesets
              uses: changesets/action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Publish to Visual Studio Marketplace
              if: steps.changesets.outputs.hasChangesets == 'false'
              uses: HaaLeo/publish-vscode-extension@v1
              with:
                  pat: ${{ secrets.VSCE_PAT }}
                  registryUrl: https://marketplace.visualstudio.com
            - name: Publish to Open VSX Registry
              if: steps.changesets.outputs.hasChangesets == 'false'
              uses: HaaLeo/publish-vscode-extension@v1
              with:
                  pat: ${{ secrets.OPEN_VSX_TOKEN }}
